# Generated by Django 5.0.14 on 2026-02-23 11:00

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                                 ('name', models.CharField(max_length=200, verbose_name='Location name')),                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Coordinates')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('visited_at', models.DateField(blank=True, null=True, verbose_name='Visited at')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['trip', 'order', 'visited_at'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=500, verbose_name='Caption')),
                ('taken_at', models.DateTimeField(blank=True, null=True, verbose_name='Taken at')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='trips.location', verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['taken_at'],
            },
        ),
        migrations.AddField(
            model_name='location',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='trips.trip', verbose_name='Trip'),
        ),
    ]
